![man](imgs

# 클래스의 중요 개념  
1. 멤버변수  
2. 생성자    
3. 메소드 (멤버함수)  
4. 인스턴스  
5. 멤버접근 연산자  
6. 상속  

In [37]:
import numpy as np

class Tensor:
    def __init__(self, input_):
        self.tensor = np.array(input_)
        self.size = self.tensor.size
        self.shape = self.tensor.shape
        
    def __add__(self, other):
        return self.tensor + other.tensor
    
    def __sub__(self, other):
        return self.tensor - other.tensor
    
    def matmul(self, other):
        return self.tensor @ other.tensor
    
    # 숙제 : element wise product 기능을 수행하는 함수를 구현하세요
    def ewp(self, other):
        return self.tensor * other.tensor
        

In [38]:
a = Tensor([[[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]], 
           [[10, 11, 12],
             [13, 14, 15],
             [16, 17, 18]], 
           [[19, 20, 21],
             [22, 23, 24],
             [25, 26, 27]]
           ])

b = Tensor([[[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]], 
           [[10, 11, 12],
             [13, 14, 15],
             [16, 17, 18]], 
           [[19, 20, 21],
             [22, 23, 24],
             [25, 26, 27]]
           ])

In [39]:
a.size

27

In [40]:
a.shape

(3, 3, 3)

In [41]:
c = a + b
print(c)

d = a - b
print(d)

[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[20 22 24]
  [26 28 30]
  [32 34 36]]

 [[38 40 42]
  [44 46 48]
  [50 52 54]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [44]:
e = a.matmul(b)
print(e)

[[[  30   36   42]
  [  66   81   96]
  [ 102  126  150]]

 [[ 435  468  501]
  [ 552  594  636]
  [ 669  720  771]]

 [[1326 1386 1446]
  [1524 1593 1662]
  [1722 1800 1878]]]


In [46]:
f = a.ewp(b)
print(f)

[[[  1   4   9]
  [ 16  25  36]
  [ 49  64  81]]

 [[100 121 144]
  [169 196 225]
  [256 289 324]]

 [[361 400 441]
  [484 529 576]
  [625 676 729]]]
